# Generated by Django 4.2.27 on 2026-02-20 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BibliotecaInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('historia', models.TextField()),
                ('historia_municipio', models.TextField()),
                ('endereco', models.TextField()),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('bibliotecaria_responsavel', models.CharField(max_length=200)),
                ('administracao_municipal', models.CharField(max_length=200)),
                ('horario_funcionamento', models.TextField()),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('data_evento', models.DateField(verbose_name='Data do Evento')),
                ('foto', models.ImageField(upload_to='eventos/', verbose_name='Foto do Evento')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-data_evento'],
            },
        ),
        migrations.CreateModel(
            name='LivroPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300, verbose_name='Título')),
                ('autor', models.CharField(max_length=200, verbose_name='Autor')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('categoria', models.CharField(choices=[('ficcao', 'Ficção'), ('nao_ficcao', 'Não-Ficção'), ('tecnico', 'Técnico'), ('didatico', 'Didático'), ('infantil', 'Infantil'), ('juvenil', 'Juvenil'), ('poesia', 'Poesia'), ('biografia', 'Biografia'), ('historia', 'História'), ('filosofia', 'Filosofia'), ('ciencia', 'Ciência'), ('arte', 'Arte'), ('outro', 'Outro')], default='outro', max_length=20, verbose_name='Categoria')),
                ('arquivo_pdf', models.FileField(upload_to='pdf_livros/', verbose_name='Arquivo PDF')),
                ('capa', models.ImageField(blank=True, null=True, upload_to='capa_livros/', verbose_name='Capa do Livro')),
                ('paginas', models.IntegerField(default=0, verbose_name='Número de Páginas')),
                ('ano_publicacao', models.IntegerField(blank=True, null=True, verbose_name='Ano de Publicação')),
                ('editora', models.CharField(blank=True, max_length=200, verbose_name='Editora')),
                ('isbn', models.CharField(blank=True, max_length=20, verbose_name='ISBN')),
                ('visualizacoes', models.IntegerField(default=0, verbose_name='Visualizações')),
                ('downloads', models.IntegerField(default=0, verbose_name='Downloads')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Livro PDF',
                'verbose_name_plural': 'Livros PDF',
                'ordering': ['-data_cadastro'],
            },
        ),
        migrations.CreateModel(
            name='Prateleira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome da Prateleira')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('categoria_associada', models.CharField(choices=[('infantil', 'Infantil'), ('juvenil', 'Juvenil'), ('adulto', 'Adulto'), ('academico', 'Acadêmico'), ('ficcao', 'Ficção'), ('nao_ficcao', 'Não-Ficção'), ('tecnico', 'Técnico'), ('didatico', 'Didático'), ('biografia', 'Biografia'), ('historia', 'História'), ('poesia', 'Poesia'), ('outro', 'Outro')], help_text='Categoria de livros que normalmente ficam nesta prateleira', max_length=20, verbose_name='Categoria Associada')),
                ('localizacao_fisica', models.CharField(blank=True, help_text='Ex: Corredor A, Seção 1', max_length=100, verbose_name='Localização Física')),
                ('capacidade_maxima', models.IntegerField(default=50, verbose_name='Capacidade Máxima')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Prateleira',
                'verbose_name_plural': 'Prateleiras',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('admin', 'Administrador'), ('funcionario', 'Funcionário'), ('usuario', 'Usuário')], default='usuario', max_length=20)),
                ('telefone', models.CharField(max_length=20)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('rua', models.CharField(max_length=200)),
                ('bairro', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=10)),
                ('cidade', models.CharField(max_length=100)),
                ('nome_mae', models.CharField(max_length=200)),
                ('nome_pai', models.CharField(blank=True, max_length=200)),
                ('visitas', models.IntegerField(default=0)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('autor', models.CharField(max_length=200)),
                ('editora', models.CharField(max_length=200)),
                ('ano_publicacao', models.IntegerField()),
                ('quantidade_paginas', models.IntegerField()),
                ('classificacao', models.CharField(choices=[('infantil', 'Infantil'), ('juvenil', 'Juvenil'), ('adulto', 'Adulto'), ('academico', 'Acadêmico')], max_length=20)),
                ('categoria', models.CharField(choices=[('ficcao', 'Ficção'), ('nao_ficcao', 'Não-Ficção'), ('tecnico', 'Técnico'), ('didatico', 'Didático'), ('biografia', 'Biografia'), ('historia', 'História'), ('poesia', 'Poesia'), ('outro', 'Outro')], max_length=20)),
                ('quantidade_total', models.IntegerField(default=1)),
                ('quantidade_disponivel', models.IntegerField(default=1)),
                ('sinopse', models.TextField(blank=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('prateleira', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='livros', to='core.prateleira', verbose_name='Prateleira')),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_devolucao_prevista', models.DateTimeField()),
                ('data_devolucao_real', models.DateTimeField(blank=True, null=True)),
                ('observacoes_devolucao', models.TextField(blank=True, null=True, verbose_name='Observações da Devolução')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('devolvido', 'Devolvido'), ('atrasado', 'Atrasado'), ('perdido', 'Perdido')], default='ativo', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.livro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
