# Generated by Django 4.2.27 on 2026-02-23 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_editora_alter_livro_editora'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoEmprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Solicitação')),
                ('data_emprestimo', models.DateTimeField(blank=True, null=True, verbose_name='Data do Empréstimo')),
                ('data_devolucao_prevista', models.DateTimeField(verbose_name='Data de Devolução Prevista')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado'), ('cancelado', 'Cancelado'), ('concluido', 'Concluído')], default='pendente', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('observacoes_admin', models.TextField(blank=True, verbose_name='Observações do Admin')),
                ('notificado', models.BooleanField(default=False, verbose_name='Notificado')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.livro', verbose_name='Livro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Solicitação de Empréstimo',
                'verbose_name_plural': 'Solicitações de Empréstimo',
                'ordering': ['-data_solicitacao'],
            },
        ),
    ]
