# Generated by Django 4.2.27 on 2026-02-24 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_solicitacaoemprestimo'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='capa',
            field=models.ImageField(blank=True, help_text='Imagem da capa do livro (formatos: JPG, PNG)', null=True, upload_to='capas_livros/', verbose_name='Capa do Livro'),
        ),
    ]
