# Generated by Django 4.2.28 on 2026-02-28 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_livro_capa'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='arquivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
        migrations.AddField(
            model_name='livro',
            name='pdf_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
